### ISSUE TITLE
Feature request: final options

### ISSUE THREAD

**Issue by meator** [crazy-complete/crazy-complete#4]
Some options (like `--help` and `--version`) can usually be considered "final" (it doesn't make sense to complete more options after them).

This is how [j4-dmenu-desktop handles it in ZSH](https://github.com/enkore/j4-dmenu-desktop/blob/7f0a72eef9671f9497e5279e11ba73d34ff014ae/etc/_j4-dmenu-desktop#L22-L23):

```zsh
    '(- *)'{-h,--help}'[print help message]' #- and * mean that no flags shall follow --help
    '(- *)--version[display program version]'
```

The relevant documentation for this behavior can be found in `zshcompsys(1)`:

> Other items may appear in the list of excluded options to indicate various other items that should not be applied when the current specification is matched: a single star (\*) for the rest arguments (i.e. a specification of the form '\*:...'); a colon (:) for all normal (non-option-) arguments; and a hyphen (-) for all options.  For example, if '(\*)' appears before an option and the option appears on the command line, the list of remaining arguments (those shown in the above table beginning with '\*:') will not be completed.

j4-dmenu-desktop doesn't implement this behavior in its Fish and Bash completion scripts.

**Comment by braph** [comment]
Hello Meator! Yes, I stumbled upon this when I was creating the project, but then I dismissed it. I grepped the ZSH-completion files for this mechanism and found that it's only used for `--help` and `--version`. I believe it's quite obvious that those options are mutually exclusive with other options. However, I’m now considering adding this to the project for the sake of completeness.

**Comment by meator** [comment]
Argparse (which is one of the input methods supported by crazy-complete), has separate `action`s for `--help` and `--version`. A similar approach could be considered for crazy-complete. In argparse, these actions have their functionality, but in crazy-complete, it could only toggle exclusivity on the flag.

Adopting this approach would mean that crazy-complete completions specified via argparse would work intuitively.

**Comment by braph** [comment]
Hello Meator!

I implemented the requested feature as you wished. The parameter is called `final`, as you suggested. It is automatically set to `true` for the help and version actions when `--input-type=python` is used. It should work as expected, so feel free to close this issue.
