### ISSUE TITLE
Feature request: add docstring support for value_list + unify interface

### ISSUE THREAD

**Issue by meator** [crazy-complete/crazy-complete#9]
I do not consider this request to be urgent or especially important.

This feature has been partially discussed in https://github.com/crazy-complete/crazy-complete/issues/5#issuecomment-2429955261. I wanted to make a separate issue for this to be able to discuss this specific change.

Currently, `value_list` entries do not support docstrings. They can be supplied by enclosing them in square brackets after the option like this `wine[compatibility with desktop files generated by Wine]`. Fish's internal `__fish_complete_list` function supports supplying docstrings for options. crazy-complete doesn't use it, so it would be more difficult to implement for Fish. Docstrings for values can be simply ignored in Bash.

If support for suboption docstrings is added, I believe that the `value_list` command should have the same interface as `choices`. Its interface is simple and clear. Reusing the same interface for `value_list` would be a positive change that would reduce complexity in my opinion.

**Comment by braph** [comment]
Hello, thanks for reminding me of that feature. I just implemented the possibility of using descriptions for values.

Of course, unifying the two interfaces would be nice, but `value_list` not only takes the values as an argument but also an optional separator.

I updated the documentation to include the new feature and also mentioned the optional `separator` parameter.
